# workflow 의 이름
name: build

# workflow 를 실행할 시점
on: push

# workflow 에서 실행할 job 들
jobs:
  build: # job의 이름
    runs-on: ubuntu-latest # job 이 실행될 환경

    steps: # job 내에서의 세부 단계
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build
